### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by savitaashture** [comment]
Failed because of connection refuse
```
TestEventListenerScale: eventlistener_scale_test.go:38: Failed to create namespace arrakis-t4bqg for tests: Post "https://api.ci-op-nn4jkjdw-d1ba8.origin-ci-int-aws.dev.rhcloud.com:6443/api/v1/namespaces": dial tcp: lookup api.ci-op-nn4jkjdw-d1ba8.origin-ci-int-aws.dev.rhcloud.com on 10.142.0.91:53: read udp 172.16.39.204:51004->10.142.0.91:53: i/o timeout
```

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
