### PR TITLE
Add midstream release notes for triggers

### PR DESCRIPTION
**Pull request by savitaashture**
added release notes for 0.7.0, 0.8.0 and 0.8.1

/cc @nikhil-thomas @khrm @Preeticp

### CODE REVIEW

**Comment by nikhil-thomas** [comment]
hi, i see that https://github.com/openshift/tektoncd-triggers/pull/275 want to merge to master,
 shall we merge to `release-v0.8.1` instead
 we can tag the merge commit as tp-1.2. what do you think

**Comment by savitaashture** [comment]
> hi, i see that #275 want to merge to master,
> shall we merge to `release-v0.8.1` instead
> we can tag the merge commit as tp-1.2. what do you think

Sure i will send PR to `release-v0.8.1`

**Comment by vdemeester** [comment]
Should they be all in the same file though ? :thinking:

**Comment by savitaashture** [comment]
I have raise PR to `release-v0.8.1` branch https://github.com/openshift/tektoncd-triggers/pull/276

**Comment by savitaashture** [comment]
> Should they be all in the same file though ?

Yep that make sense as per this discussion https://coreos.slack.com/archives/C011AMWJSUX/p1601276552018500?thread_ts=1601275654.015800&cid=C011AMWJSUX also

**Pull request closed without merging**
