### PR TITLE
:robot: Triggering CI on branch 'release-next' after synching to upstream/master

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by concaf** [comment]
@piyush-garg pointed that this might be related to https://github.com/tektoncd/triggers/pull/976, yet to look into it. @savitaashture WDYT?

**Comment by savitaashture** [comment]
> @piyush-garg pointed that this might be related to [tektoncd#976](https://github.com/tektoncd/triggers/pull/976), yet to look into it. @savitaashture WDYT?

Oh ya when i check the logs i see

```
unable to recognize "tekton-triggers-resolved.yaml": no matches for kind "ClusterInterceptor" in version "triggers.tekton.dev/v1alpha1"
unable to recognize "tekton-triggers-resolved.yaml": no matches for kind "ClusterInterceptor" in version "triggers.tekton.dev/v1alpha1"
unable to recognize "tekton-triggers-resolved.yaml": no matches for kind "ClusterInterceptor" in version "triggers.tekton.dev/v1alpha1"
unable to recognize "tekton-triggers-resolved.yaml": no matches for kind "ClusterInterceptor" in version "triggers.tekton.dev/v1alpha1"
```

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
