### PR TITLE
Add release yamls for 0.14.2

### PR DESCRIPTION
**Pull request by savitaashture**
/cc @nikhil-thomas @khrm

### CODE REVIEW

**Comment by savitaashture** [comment]
Some issue with route53

```
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: timeout while waiting for state to become 'INSYNC' (last state: 'PENDING', timeout: 30m0s)
level=error
level=error msg=  on ../tmp/openshift-install-711386269/route53/base.tf line 70, in resource "aws_route53_record" "api_external_internal_zone_alias":
level=error msg=  70: resource "aws_route53_record" "api_external_internal_zone_alias" {
level=error
level=error
level=fatal msg=failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
Setup phase finished, prepare env for next steps
```

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
